#!/bin/bash

verilator --trace \
   --cc rtl/x_23K640_multiple.sv \
   --cc 23K640/rtl/x_23K640_sck.sv \
   --cc 23K640/rtl/x_23K640_data.sv \
   --cc rtl/x_memxbar.sv \
   --exe verif/x_23K640_multiple_tb.cpp 

make -C obj_dir -f Vx_23K640_multiple.mk Vx_23K640_multiple

