#!/bin/bash

verilator --trace \
   --cc rtl/x_23K640_multiple.sv \
   --cc 23K640/rtl/x_23K640_sck.sv \
   --cc 23K640/rtl/x_23K640_data.sv \
   --cc 23K640/verif/app_driver.cpp \
   --cc 23K640/verif/sram_model.cpp \
   --cc 23K640/verif/logger.cpp \
   --cc rtl/x_buf.sv \
   --cc rtl/x_req_cpl_buf.sv \
   --cc rtl/x_memxbar.sv \
   --exe verif/x_23K640_multiple_tb.cpp \
   -I23K640/verif/include/


make -C obj_dir -f Vx_23K640_multiple.mk Vx_23K640_multiple

